[sample/http] fix build error of "missing-brackets"
Fix below build error with gcc-4.8.5:

    http/http-example.c: In function ‘main’:
    http/http-example.c:74:5: error: missing braces around initializer [-Werror=missing-braces]
         iotx_device_info_t device_info = {0};
         ^
    http/http-example.c:74:5: error: (near initialization for ‘device_info.product_key’) [-Werror=missing-braces]

Signed-off-by: Yang, Xiao <yusheng.yx@alibaba-inc.com>